### PR TITLE
Trying to add picture to alum page

### PR DESCRIPTION
**Pull request by hancha**

### CODE REVIEW

**Comment by bmw9t** [comment]
Yay! I had to tweak the path to the image to be lowercase, but you're up there now! Thanks! Hope you're well.

**Comment by hancha** [comment]
Thanks, Brandon! Took long enough, am I right?

Checked out Prism while you were working on it yesterday to show a grad
student here... it was back up and and running within the day. What a
coincidence!

Hope everything's well with you too.

Best,

Hannah

Hannah Joy Chapman
Research & Learning Services
Olin Library 106
Cornell University
607-254-7481
hjc75@cornell.edu

**Comment by bmw9t** [comment]
Not long at all! That's funny about Prism - we had to update the way that the Facebook logins were using. Should all be sorted now though. Hope you still found time to show the grad student!

**Comment by hancha** [comment]
I did! And sent her an email later containing the links and such. The
student is formulating her teaching strategies and envisioned a tool where
her class could all sign in to an online (gated or non) text and make
comments and highlights and be able to use that as a tool to spark
discussion.

-Hannah

**Pull request merged**
